[workspace]
members = ["daemon", "cli", "core"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
tokio = { version = "1.48", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
itertools = { version = "0.14" }
thiserror = { version = "2.0.17" }
tracing = { version = "0.1" }
derive_more = { version = "2", features = ["display"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = { version = "0.2" }
bytes = { version = "1.11.0" }
