[workspace]
members = [
"daemon", "cli", "core"
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
tokio = { version = "1.41", features = ["full"]}
serde = {version = "1.0", features = ["derive"]}
itertools = {version = "0.14.0"}
